/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/consumers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Consumer resources.
         * @description Retrieves the collection of Consumer resources.
         */
        get: operations["api_consumers_get_collection"];
        put?: never;
        /**
         * Creates a Consumer resource.
         * @description Creates a Consumer resource.
         */
        post: operations["api_consumers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consumers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Consumer resource.
         * @description Retrieves a Consumer resource.
         */
        get: operations["api_consumers_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the Consumer resource.
         * @description Removes the Consumer resource.
         */
        delete: operations["api_consumers_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the Consumer resource.
         * @description Updates the Consumer resource.
         */
        patch: operations["api_consumers_id_patch"];
        trace?: never;
    };
    "/api/field_instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of FieldInstance resources.
         * @description Retrieves the collection of FieldInstance resources.
         */
        get: operations["api_field_instances_get_collection"];
        put?: never;
        /**
         * Creates a FieldInstance resource.
         * @description Creates a FieldInstance resource.
         */
        post: operations["api_field_instances_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/field_instances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a FieldInstance resource.
         * @description Retrieves a FieldInstance resource.
         */
        get: operations["api_field_instances_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the FieldInstance resource.
         * @description Removes the FieldInstance resource.
         */
        delete: operations["api_field_instances_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the FieldInstance resource.
         * @description Updates the FieldInstance resource.
         */
        patch: operations["api_field_instances_id_patch"];
        trace?: never;
    };
    "/api/field_types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of FieldType resources.
         * @description Retrieves the collection of FieldType resources.
         */
        get: operations["api_field_types_get_collection"];
        put?: never;
        /**
         * Creates a FieldType resource.
         * @description Creates a FieldType resource.
         */
        post: operations["api_field_types_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/field_types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a FieldType resource.
         * @description Retrieves a FieldType resource.
         */
        get: operations["api_field_types_id_get"];
        /**
         * Replaces the FieldType resource.
         * @description Replaces the FieldType resource.
         */
        put: operations["api_field_types_id_put"];
        post?: never;
        /**
         * Removes the FieldType resource.
         * @description Removes the FieldType resource.
         */
        delete: operations["api_field_types_id_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/form_definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of FormDefinition resources.
         * @description Retrieves the collection of FormDefinition resources.
         */
        get: operations["api_form_definitions_get_collection"];
        put?: never;
        /**
         * Creates a FormDefinition resource.
         * @description Creates a FormDefinition resource.
         */
        post: operations["api_form_definitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/form_definitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a FormDefinition resource.
         * @description Retrieves a FormDefinition resource.
         */
        get: operations["api_form_definitions_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the FormDefinition resource.
         * @description Removes the FormDefinition resource.
         */
        delete: operations["api_form_definitions_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the FormDefinition resource.
         * @description Updates the FormDefinition resource.
         */
        patch: operations["api_form_definitions_id_patch"];
        trace?: never;
    };
    "/api/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates a Submission resource.
         * @description Creates a Submission resource.
         */
        post: operations["api_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Unprocessable entity */
        ConstraintViolation: {
            /** @default 422 */
            status: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath?: string;
                /** @description The message associated with the violation */
                message?: string;
            }[];
            readonly detail?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        /** @description Unprocessable entity */
        "ConstraintViolation.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @default 422 */
            status: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath?: string;
                /** @description The message associated with the violation */
                message?: string;
            }[];
            readonly detail?: string;
            readonly description?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        Consumer: {
            readonly id?: number;
            name?: string;
            apiKey?: string;
            contactEmail?: string;
            allowedOrigins?: (string | null)[];
            readonly roles?: (string | null)[];
            readonly userIdentifier?: string;
        };
        "Consumer.html": {
            readonly id?: number;
            name?: string;
            apiKey?: string;
            contactEmail?: string;
            allowedOrigins?: (string | null)[];
            readonly roles?: (string | null)[];
            readonly userIdentifier?: string;
        };
        "Consumer.jsonMergePatch": {
            readonly id?: number;
            name?: string;
            apiKey?: string;
            contactEmail?: string;
            allowedOrigins?: (string | null)[];
            readonly roles?: (string | null)[];
            readonly userIdentifier?: string;
        };
        "Consumer.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            name?: string;
            apiKey?: string;
            contactEmail?: string;
            allowedOrigins?: (string | null)[];
            readonly roles?: (string | null)[];
            readonly userIdentifier?: string;
        };
        "Consumer.yaml": {
            readonly id?: number;
            name?: string;
            apiKey?: string;
            contactEmail?: string;
            allowedOrigins?: (string | null)[];
            readonly roles?: (string | null)[];
            readonly userIdentifier?: string;
        };
        /** @description A representation of common errors. */
        Error: {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string;
            /**
             * @default 400
             * @example 404
             */
            status: number;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
        };
        /** @description A representation of common errors. */
        "Error.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string;
            /**
             * @default 400
             * @example 404
             */
            status: number;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
            readonly description?: string | null;
        };
        FieldInstance: {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            form?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            component?: string;
            name?: string;
            label?: string;
            /** @default 0 */
            position: number;
            validationRules?: (string | null)[];
            uiOptions?: (string | null)[];
            /** @default default */
            renderStrategy: string;
            renderOptions?: (string | null)[];
        };
        "FieldInstance.html": {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            form?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            component?: string;
            name?: string;
            label?: string;
            /** @default 0 */
            position: number;
            validationRules?: (string | null)[];
            uiOptions?: (string | null)[];
            /** @default default */
            renderStrategy: string;
            renderOptions?: (string | null)[];
        };
        "FieldInstance.jsonMergePatch": {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            form?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            component?: string;
            name?: string;
            label?: string;
            /** @default 0 */
            position: number;
            validationRules?: (string | null)[];
            uiOptions?: (string | null)[];
            /** @default default */
            renderStrategy: string;
            renderOptions?: (string | null)[];
        };
        "FieldInstance.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            form?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            component?: string;
            name?: string;
            label?: string;
            /** @default 0 */
            position: number;
            validationRules?: (string | null)[];
            uiOptions?: (string | null)[];
            /** @default default */
            renderStrategy: string;
            renderOptions?: (string | null)[];
        };
        "FieldInstance.yaml": {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            form?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            component?: string;
            name?: string;
            label?: string;
            /** @default 0 */
            position: number;
            validationRules?: (string | null)[];
            uiOptions?: (string | null)[];
            /** @default default */
            renderStrategy: string;
            renderOptions?: (string | null)[];
        };
        "FieldType-field_type.read": {
            readonly id?: number;
            slug: string;
            label: string;
            icon?: string | null;
            description?: string | null;
            /**
             * @default string
             * @enum {string}
             */
            dataType: "string" | "integer" | "float" | "boolean" | "array" | "json" | "date_time";
            component: string;
            assets?: (string | null)[] | null;
            initHook?: string | null;
            configurationSchema?: (string | null)[];
            defaultConfiguration?: (string | null)[];
            /**
             * @default text
             * @enum {string}
             */
            presentationType: "text" | "html" | "date" | "datetime" | "bool" | "image" | "file" | "hidden";
            presentationConfiguration?: (string | null)[];
        };
        "FieldType-field_type.write": {
            slug: string;
            label: string;
            icon?: string | null;
            description?: string | null;
            /**
             * @default string
             * @enum {string}
             */
            dataType: "string" | "integer" | "float" | "boolean" | "array" | "json" | "date_time";
            component: string;
            assets?: (string | null)[] | null;
            initHook?: string | null;
            configurationSchema?: (string | null)[];
            defaultConfiguration?: (string | null)[];
            /**
             * @default text
             * @enum {string}
             */
            presentationType: "text" | "html" | "date" | "datetime" | "bool" | "image" | "file" | "hidden";
            presentationConfiguration?: (string | null)[];
        };
        "FieldType.html-field_type.read": {
            readonly id?: number;
            slug: string;
            label: string;
            icon?: string | null;
            description?: string | null;
            /**
             * @default string
             * @enum {string}
             */
            dataType: "string" | "integer" | "float" | "boolean" | "array" | "json" | "date_time";
            component: string;
            assets?: (string | null)[] | null;
            initHook?: string | null;
            configurationSchema?: (string | null)[];
            defaultConfiguration?: (string | null)[];
            /**
             * @default text
             * @enum {string}
             */
            presentationType: "text" | "html" | "date" | "datetime" | "bool" | "image" | "file" | "hidden";
            presentationConfiguration?: (string | null)[];
        };
        "FieldType.jsonld-field_type.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            slug: string;
            label: string;
            icon?: string | null;
            description?: string | null;
            /**
             * @default string
             * @enum {string}
             */
            dataType: "string" | "integer" | "float" | "boolean" | "array" | "json" | "date_time";
            component: string;
            assets?: (string | null)[] | null;
            initHook?: string | null;
            configurationSchema?: (string | null)[];
            defaultConfiguration?: (string | null)[];
            /**
             * @default text
             * @enum {string}
             */
            presentationType: "text" | "html" | "date" | "datetime" | "bool" | "image" | "file" | "hidden";
            presentationConfiguration?: (string | null)[];
        };
        "FieldType.yaml-field_type.read": {
            readonly id?: number;
            slug: string;
            label: string;
            icon?: string | null;
            description?: string | null;
            /**
             * @default string
             * @enum {string}
             */
            dataType: "string" | "integer" | "float" | "boolean" | "array" | "json" | "date_time";
            component: string;
            assets?: (string | null)[] | null;
            initHook?: string | null;
            configurationSchema?: (string | null)[];
            defaultConfiguration?: (string | null)[];
            /**
             * @default text
             * @enum {string}
             */
            presentationType: "text" | "html" | "date" | "datetime" | "bool" | "image" | "file" | "hidden";
            presentationConfiguration?: (string | null)[];
        };
        FormDefinition: {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            consumer?: string;
            code?: string;
            fields?: string[];
            webhookUrl?: string | null;
        };
        "FormDefinition.html": {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            consumer?: string;
            code?: string;
            fields?: string[];
            webhookUrl?: string | null;
        };
        "FormDefinition.jsonMergePatch": {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            consumer?: string;
            code?: string;
            fields?: string[];
            webhookUrl?: string | null;
        };
        "FormDefinition.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            consumer?: string;
            code?: string;
            fields?: string[];
            webhookUrl?: string | null;
        };
        "FormDefinition.yaml": {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            consumer?: string;
            code?: string;
            fields?: string[];
            webhookUrl?: string | null;
        };
        HydraCollectionBaseSchema: components["schemas"]["HydraCollectionBaseSchemaNoPagination"] & {
            /**
             * @example {
             *       "@id": "string",
             *       "type": "string",
             *       "first": "string",
             *       "last": "string",
             *       "previous": "string",
             *       "next": "string"
             *     }
             */
            view?: {
                /** Format: iri-reference */
                "@id"?: string;
                "@type"?: string;
                /** Format: iri-reference */
                first?: string;
                /** Format: iri-reference */
                last?: string;
                /** Format: iri-reference */
                previous?: string;
                /** Format: iri-reference */
                next?: string;
            };
        };
        HydraCollectionBaseSchemaNoPagination: {
            totalItems?: number;
            search?: {
                "@type"?: string;
                template?: string;
                variableRepresentation?: string;
                mapping?: {
                    "@type"?: string;
                    variable?: string;
                    property?: string | null;
                    required?: boolean;
                }[];
            };
        };
        HydraItemBaseSchema: {
            "@context"?: string | ({
                "@vocab": string;
                /** @enum {string} */
                hydra: "http://www.w3.org/ns/hydra/core#";
            } & {
                [key: string]: unknown;
            });
            "@id": string;
            "@type": string;
        };
        Submission: {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            form?: string;
            data?: (string | null)[];
            /** Format: date-time */
            createdAt?: string;
            rawPayload?: (string | null)[] | null;
        };
        "Submission.html": {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            form?: string;
            data?: (string | null)[];
            /** Format: date-time */
            createdAt?: string;
            rawPayload?: (string | null)[] | null;
        };
        "Submission.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            form?: string;
            data?: (string | null)[];
            /** Format: date-time */
            createdAt?: string;
            rawPayload?: (string | null)[] | null;
        };
        "Submission.yaml": {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            form?: string;
            data?: (string | null)[];
            /** Format: date-time */
            createdAt?: string;
            rawPayload?: (string | null)[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_consumers_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consumer collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consumer"][];
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Consumer.jsonld"][];
                    };
                    "text/html": components["schemas"]["Consumer.html"][];
                    "application/x-yaml": components["schemas"]["Consumer.yaml"][];
                };
            };
        };
    };
    api_consumers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Consumer resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["Consumer"];
                "application/ld+json": components["schemas"]["Consumer"];
                "text/html": components["schemas"]["Consumer"];
                "application/x-yaml": components["schemas"]["Consumer"];
            };
        };
        responses: {
            /** @description Consumer resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consumer"];
                    "application/ld+json": components["schemas"]["Consumer.jsonld"];
                    "text/html": components["schemas"]["Consumer.html"];
                    "application/x-yaml": components["schemas"]["Consumer.yaml"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_consumers_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Consumer identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consumer resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consumer"];
                    "application/ld+json": components["schemas"]["Consumer.jsonld"];
                    "text/html": components["schemas"]["Consumer.html"];
                    "application/x-yaml": components["schemas"]["Consumer.yaml"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_consumers_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Consumer identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consumer resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_consumers_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Consumer identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Consumer resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["Consumer.jsonMergePatch"];
            };
        };
        responses: {
            /** @description Consumer resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consumer"];
                    "application/ld+json": components["schemas"]["Consumer.jsonld"];
                    "text/html": components["schemas"]["Consumer.html"];
                    "application/x-yaml": components["schemas"]["Consumer.yaml"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_field_instances_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FieldInstance collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldInstance"][];
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["FieldInstance.jsonld"][];
                    };
                    "text/html": components["schemas"]["FieldInstance.html"][];
                    "application/x-yaml": components["schemas"]["FieldInstance.yaml"][];
                };
            };
        };
    };
    api_field_instances_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new FieldInstance resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldInstance"];
                "application/ld+json": components["schemas"]["FieldInstance"];
                "text/html": components["schemas"]["FieldInstance"];
                "application/x-yaml": components["schemas"]["FieldInstance"];
            };
        };
        responses: {
            /** @description FieldInstance resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldInstance"];
                    "application/ld+json": components["schemas"]["FieldInstance.jsonld"];
                    "text/html": components["schemas"]["FieldInstance.html"];
                    "application/x-yaml": components["schemas"]["FieldInstance.yaml"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_field_instances_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description FieldInstance identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FieldInstance resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldInstance"];
                    "application/ld+json": components["schemas"]["FieldInstance.jsonld"];
                    "text/html": components["schemas"]["FieldInstance.html"];
                    "application/x-yaml": components["schemas"]["FieldInstance.yaml"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_field_instances_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description FieldInstance identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FieldInstance resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_field_instances_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description FieldInstance identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated FieldInstance resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["FieldInstance.jsonMergePatch"];
            };
        };
        responses: {
            /** @description FieldInstance resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldInstance"];
                    "application/ld+json": components["schemas"]["FieldInstance.jsonld"];
                    "text/html": components["schemas"]["FieldInstance.html"];
                    "application/x-yaml": components["schemas"]["FieldInstance.yaml"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_field_types_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FieldType collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldType-field_type.read"][];
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["FieldType.jsonld-field_type.read"][];
                    };
                    "text/html": components["schemas"]["FieldType.html-field_type.read"][];
                    "application/x-yaml": components["schemas"]["FieldType.yaml-field_type.read"][];
                };
            };
        };
    };
    api_field_types_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new FieldType resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldType-field_type.write"];
                "application/ld+json": components["schemas"]["FieldType-field_type.write"];
                "text/html": components["schemas"]["FieldType-field_type.write"];
                "application/x-yaml": components["schemas"]["FieldType-field_type.write"];
            };
        };
        responses: {
            /** @description FieldType resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldType-field_type.read"];
                    "application/ld+json": components["schemas"]["FieldType.jsonld-field_type.read"];
                    "text/html": components["schemas"]["FieldType.html-field_type.read"];
                    "application/x-yaml": components["schemas"]["FieldType.yaml-field_type.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_field_types_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description FieldType identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FieldType resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldType-field_type.read"];
                    "application/ld+json": components["schemas"]["FieldType.jsonld-field_type.read"];
                    "text/html": components["schemas"]["FieldType.html-field_type.read"];
                    "application/x-yaml": components["schemas"]["FieldType.yaml-field_type.read"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_field_types_id_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description FieldType identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated FieldType resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldType-field_type.write"];
                "application/ld+json": components["schemas"]["FieldType-field_type.write"];
                "text/html": components["schemas"]["FieldType-field_type.write"];
                "application/x-yaml": components["schemas"]["FieldType-field_type.write"];
            };
        };
        responses: {
            /** @description FieldType resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldType-field_type.read"];
                    "application/ld+json": components["schemas"]["FieldType.jsonld-field_type.read"];
                    "text/html": components["schemas"]["FieldType.html-field_type.read"];
                    "application/x-yaml": components["schemas"]["FieldType.yaml-field_type.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_field_types_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description FieldType identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FieldType resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_form_definitions_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FormDefinition collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormDefinition"][];
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["FormDefinition.jsonld"][];
                    };
                    "text/html": components["schemas"]["FormDefinition.html"][];
                    "application/x-yaml": components["schemas"]["FormDefinition.yaml"][];
                };
            };
        };
    };
    api_form_definitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new FormDefinition resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormDefinition"];
                "application/ld+json": components["schemas"]["FormDefinition"];
                "text/html": components["schemas"]["FormDefinition"];
                "application/x-yaml": components["schemas"]["FormDefinition"];
            };
        };
        responses: {
            /** @description FormDefinition resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormDefinition"];
                    "application/ld+json": components["schemas"]["FormDefinition.jsonld"];
                    "text/html": components["schemas"]["FormDefinition.html"];
                    "application/x-yaml": components["schemas"]["FormDefinition.yaml"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_form_definitions_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description FormDefinition identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FormDefinition resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormDefinition"];
                    "application/ld+json": components["schemas"]["FormDefinition.jsonld"];
                    "text/html": components["schemas"]["FormDefinition.html"];
                    "application/x-yaml": components["schemas"]["FormDefinition.yaml"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_form_definitions_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description FormDefinition identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FormDefinition resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_form_definitions_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description FormDefinition identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated FormDefinition resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["FormDefinition.jsonMergePatch"];
            };
        };
        responses: {
            /** @description FormDefinition resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormDefinition"];
                    "application/ld+json": components["schemas"]["FormDefinition.jsonld"];
                    "text/html": components["schemas"]["FormDefinition.html"];
                    "application/x-yaml": components["schemas"]["FormDefinition.yaml"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_submissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Submission resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["Submission"];
                "application/ld+json": components["schemas"]["Submission"];
                "text/html": components["schemas"]["Submission"];
                "application/x-yaml": components["schemas"]["Submission"];
            };
        };
        responses: {
            /** @description Submission resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                    "application/ld+json": components["schemas"]["Submission.jsonld"];
                    "text/html": components["schemas"]["Submission.html"];
                    "application/x-yaml": components["schemas"]["Submission.yaml"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
}
