<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251121120803 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE consumer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, api_key VARCHAR(255) NOT NULL, contact_email VARCHAR(255) NOT NULL, allowed_origins JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_705B3727C912ED9D ON consumer (api_key)');
        $this->addSql('CREATE TABLE field_instance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, position INT NOT NULL, validation_rules JSON NOT NULL, ui_options JSON NOT NULL, render_strategy VARCHAR(50) NOT NULL, render_options JSON NOT NULL, form_id INT NOT NULL, component_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_940836135FF69B7D ON field_instance (form_id)');
        $this->addSql('CREATE INDEX IDX_94083613E2ABAFFF ON field_instance (component_id)');
        $this->addSql('CREATE TABLE field_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL, icon VARCHAR(50) DEFAULT NULL, description TEXT DEFAULT NULL, data_type VARCHAR(20) NOT NULL, component VARCHAR(50) NOT NULL, assets JSON DEFAULT NULL, init_hook VARCHAR(50) DEFAULT NULL, configuration_schema JSON NOT NULL, default_configuration JSON NOT NULL, presentation_type VARCHAR(20) NOT NULL, presentation_configuration JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F123E93989D9B62 ON field_type (slug)');
        $this->addSql('CREATE TABLE form_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, webhook_url VARCHAR(255) DEFAULT NULL, consumer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_61F7634C77153098 ON form_definition (code)');
        $this->addSql('CREATE INDEX IDX_61F7634C37FDBD6D ON form_definition (consumer_id)');
        $this->addSql('CREATE TABLE submission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, data JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, form_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB055AF35FF69B7D ON submission (form_id)');
        $this->addSql('ALTER TABLE field_instance ADD CONSTRAINT FK_940836135FF69B7D FOREIGN KEY (form_id) REFERENCES form_definition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE field_instance ADD CONSTRAINT FK_94083613E2ABAFFF FOREIGN KEY (component_id) REFERENCES field_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE form_definition ADD CONSTRAINT FK_61F7634C37FDBD6D FOREIGN KEY (consumer_id) REFERENCES consumer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE submission ADD CONSTRAINT FK_DB055AF35FF69B7D FOREIGN KEY (form_id) REFERENCES form_definition (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE field_instance DROP CONSTRAINT FK_940836135FF69B7D');
        $this->addSql('ALTER TABLE field_instance DROP CONSTRAINT FK_94083613E2ABAFFF');
        $this->addSql('ALTER TABLE form_definition DROP CONSTRAINT FK_61F7634C37FDBD6D');
        $this->addSql('ALTER TABLE submission DROP CONSTRAINT FK_DB055AF35FF69B7D');
        $this->addSql('DROP TABLE consumer');
        $this->addSql('DROP TABLE field_instance');
        $this->addSql('DROP TABLE field_type');
        $this->addSql('DROP TABLE form_definition');
        $this->addSql('DROP TABLE submission');
    }
}
